syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.marketplace.proto.customer";
option java_outer_classname = "CustomerAuthProto";

service CustomerService {
  rpc FindCustomerByUsername (CustomerByUsernameRequest) returns (CustomerAuthResponse);
  rpc CreateCustomer (CreateCustomerRequest) returns (CreateCustomerResponse);
}

message CustomerByUsernameRequest {
  string username = 1;
}

message CustomerAuthResponse {
  bool exists = 1;
  string userId = 2;
  string username = 3;
  string passwordHash = 4;
}

message CreateCustomerRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}

message CreateCustomerResponse {
  string message = 1;
}
