spring.application.name=order-service
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=order-service
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port=8081
