spring.application.name=order-service
spring.jpa.open-in-view=false
server.port=8081
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=order-service
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true