spring.application.name=Auth Service
jwt.secret: V0hZX0FSRV9ZT1VfR0FZNDNfV0hZQVJFWU9VR0FZWVlZWVlZWVlZWVlZWVlZWVlZWVkyMjIxMTIxMgo=
# ${JWT_SECRET}

jwt.expiration-ms: 3600000
server.port:8282
grpc.client.customer.address=static://localhost:9090
grpc.client.customer.negotiationType=plaintext
