spring.application.name=Analytics logging service

spring.datasource.url=jdbc:postgresql://localhost:5450/analytics_db
spring.datasource.username=analytics_user
spring.datasource.password=analytics_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=analytics-service
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.jdbc.core=INFO
