spring.application.name=product-service
spring.mongodb.uri=mongodb://productuser:productpass@localhost:27017/product-service?authSource=product-service
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
